# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-06 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170522_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='showNum',
            field=models.BigIntegerField(default=0),
        ),
    ]
